version: '3'
services:
  web:
    build: ./
    networks:
      - flask
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: example
    volumes:
       - postgredb:/var/lib/postgresql/data
    networks:
      - flask
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
    networks:
      - flask
networks:
  flask:
    driver: bridge
volumes:
  postgredb: